// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vibrant.QuerySearch.ConsoleApp;

namespace Vibrant.QuerySearch.ConsoleApp.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20180830112338_RefClass")]
    partial class RefClass
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Vibrant.QuerySearch.ConsoleApp.MyClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SomeText");

                    b.HasKey("Id");

                    b.ToTable("MyClasses");
                });

            modelBuilder.Entity("Vibrant.QuerySearch.ConsoleApp.MyRefClass", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("Whatver");

                    b.HasKey("Id");

                    b.ToTable("MyRefClasses");
                });

            modelBuilder.Entity("Vibrant.QuerySearch.ConsoleApp.MyRefClass", b =>
                {
                    b.HasOne("Vibrant.QuerySearch.ConsoleApp.MyClass", "MyClass")
                        .WithOne("MyRefClass")
                        .HasForeignKey("Vibrant.QuerySearch.ConsoleApp.MyRefClass", "Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
